services:
  - type: web
    name: blog-backend
    runtime: python
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yourdomain.onrender.com"
      - key: PORT
        value: "8000"
    buildCommand: "pip install -r blog_backend/requirements.txt"
    startCommand: "gunicorn blog_backend.wsgi:application --bind 0.0.0.0:8000"

