services:
  - name: blog-backend
    type: web
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn blog_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
      - key: DEBUG
        value: "False"
