# Generated by Django 5.1.4 on 2024-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
