# Generated by Django 5.1.4 on 2024-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_issued', models.DateField()),
                ('certificate_link', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certificates/thumbnails/')),
            ],
        ),
    ]
