# Generated by Django 4.2 on 2025-03-22 05:17

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('blog_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
