# Generated by Django 5.1.4 on 2024-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_blog_link_remove_project_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
