# Generated by Django 3.1.1 on 2024-12-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
