# Generated by Django 5.1.4 on 2024-12-11 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20241203_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Tech', 'Tech')], default='Tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, default='Anonymous', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
