# Generated by Django 5.1.4 on 2024-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_id'),
    ]

    #operations = [
     #   migrations.AlterField(
      #      model_name='blog',
       #     name='id',
       #     field=models.BigAutoField(primary_key=True, serialize=False),
       # ),
   # ]
