# Generated by Django 5.1.4 on 2024-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_id'),
    ]

  