# Generated by Django 5.1.4 on 2024-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_id'),
    ]

    